[package]
name = "fanman"
version = "0.1.0"
edition = "2024"
authors = ["Chris Flinn <christopher.flinn@gmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
nix = { version = "0.29", features = ["ioctl"] }
anyhow = "1.0"
thiserror = "1.0"
